management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8082
spring:
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest
    cloud:
        bus:
            id: ${spring.application.name}:${server.port}:arun
            trace:
                enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
  instance:
    hostname: localhost